### ISSUE TITLE
Better exception when re-initializing

### ISSUE THREAD

**Issue by jarcec** [jarcec/cir#10]
```
/Users/jarcec/.rvm/gems/ruby-2.4.0-rc1/gems/cir-0.0.99/lib/cir/git_repository.rb:24:in `create': Path /Users/jarcec/.cir/repository already exists. (Cir::Exception::RepositoryExists)
	from /Users/jarcec/.rvm/gems/ruby-2.4.0-rc1/gems/cir-0.0.99/lib/cir/repository.rb:27:in `create'
```

**Comment by jarcec** [comment]
Done.
